POST http://localhost:3000/api/assets
Content-Type: application/json

{
  "id": "asset_id_01",
  "symbol": "asset_symbol_01"
}

###
GET http://localhost:3000/api/assets
content-type: application/json

###
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "asset_id": "asset_id_02",
  "price": 150,
  "status": "open"
}

###
GET http://localhost:3000/api/orders
content-type: application/json